USE gsb;

CREATE TABLE IF NOT EXISTS `STOCKER` (
	`VISITEUR` varchar(6) NOT NULL,
    `MEDICAMENT` varchar(25) NOT NULL,
	`QUANTITE` int NOT NULL,
	KEY `VISITEUR` (`VISITEUR`),
    KEY `MEDICAMENT` (`MEDICAMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `STOCKER` ADD CONSTRAINT `STOCKER_ibfk_1` FOREIGN KEY (`VISITEUR`) REFERENCES `VISITEUR` (`MATRICULE`);
ALTER TABLE `STOCKER` ADD CONSTRAINT `STOCKER_ibfk_2` FOREIGN KEY (`MEDICAMENT`) REFERENCES `MEDICAMENT` (`MED_DEPOTLEGAL`);


CREATE TABLE IF NOT EXISTS `OFFRIR` (
	`VISITE` varchar(8) NOT NULL,
    `MEDICAMENT` varchar(25) NOT NULL,
	`QUANTITE` int NOT NULL,
	KEY `VISITE` (`VISITE`),
    KEY `MEDICAMENT` (`MEDICAMENT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE `OFFRIR` ADD CONSTRAINT `OFFRIR_ibfk_1` FOREIGN KEY (`VISITE`) REFERENCES `VISITE` (`REFERENCE`);
ALTER TABLE `OFFRIR` ADD CONSTRAINT `OFFRIR_ibfk_2` FOREIGN KEY (`MEDICAMENT`) REFERENCES `MEDICAMENT` (`MED_DEPOTLEGAL`);